version: '3'
services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    ports:
      - 8080:8080
    networks:
      - my-network

networks:
  my-network:
    driver: bridge