version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - mariadb
    networks:
      - backend
  mariadb:
    image: "mariadb:latest"
    restart: always
    ports:
      - 3307:3306
    networks:
      - backend
    environment:
      MARIADB_HOST: mariadb
      MYSQL_DATABASE: church 
      MARIADB_USER: root
      MARIADB_PASSWORD: P@ssw0rd
      MARIADB_ROOT_PASSWORD: P@ssw0rd
networks:
  backend: